# Generated by Django 6.0.6 on 2026-08-05 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_acquisition_review_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.PositiveIntegerField()),
                ('minted_at', models.DateTimeField(auto_now_add=True)),
                ('metadata_hash', models.CharField(max_length=64, unique=True)),
                ('is_listed_for_resale', models.BooleanField(default=False)),
                ('resale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_tokens_owned', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_tokens', to='resources.resource')),
            ],
            options={
                'ordering': ['token_number'],
                'unique_together': {('resource', 'token_number')},
            },
        ),
        migrations.CreateModel(
            name='NFTSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('primary', 'Primary Sale'), ('secondary', 'Secondary Sale / Resale')], default='primary', max_length=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('royalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seller_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creator_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_purchases', to=settings.AUTH_USER_MODEL)),
                ('original_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_royalties_earned', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_sold', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='resources.nfttoken')),
            ],
            options={
                'ordering': ['-sold_at'],
            },
        ),
    ]
