# Generated by Django 6.0.6 on 2026-08-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_acquisition_paid_amount_acquisition_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfttoken',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Acquisition',
        ),
    ]
