# Generated by Django 6.0.6 on 2026-08-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_backfill_nfttoken_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_selling_paused',
            field=models.BooleanField(default=False),
        ),
    ]
